---
require:
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rubycw

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 16

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Max: 20

Bundler/GemComment:
  Enabled: false
  Include:
    - Gemfile

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Rubycw/Rubycw:
  Exclude:
    - ./*.md

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

AllCops:
  Exclude:
    - bin/*
