---
Metrics/MethodLength:
  Max: 16

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Max: 20

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/ExampleLength:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - vendor/**/*
