---
Metrics/MethodLength:
  Max: 16

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Max: 20

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

AllCops:
  Exclude:
    - bin/*
